// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_us_news/test/app/logic/news/item/news_item_get_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_us_news/src/domain/dto/news/news_item.dart' as _i2;
import 'package:flutter_us_news/src/domain/uscases/news/item/news_item_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNewsItem_0 extends _i1.SmartFake implements _i2.NewsItem {
  _FakeNewsItem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NewsItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsItemUseCase extends _i1.Mock implements _i3.NewsItemUseCase {
  MockNewsItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NewsItem> invoke(String? newsID) => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [newsID],
        ),
        returnValue: _i4.Future<_i2.NewsItem>.value(_FakeNewsItem_0(
          this,
          Invocation.method(
            #invoke,
            [newsID],
          ),
        )),
      ) as _i4.Future<_i2.NewsItem>);
}
