// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_us_news/test/domain/usecases/news/list/news_list_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_us_news/src/domain/dto/news/news_item.dart' as _i4;
import 'package:flutter_us_news/src/domain/dto/sort/sort_by.dart' as _i5;
import 'package:flutter_us_news/src/domain/repositories/news/list/news_list_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NewsListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsListRepository extends _i1.Mock
    implements _i2.NewsListRepository {
  MockNewsListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.NewsItem>> getNewsList({
    required int? from,
    required int? to,
    required List<String>? queries,
    required _i5.SortBy? sortBy,
    required int? pageNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNewsList,
          [],
          {
            #from: from,
            #to: to,
            #queries: queries,
            #sortBy: sortBy,
            #pageNumber: pageNumber,
          },
        ),
        returnValue: _i3.Future<List<_i4.NewsItem>>.value(<_i4.NewsItem>[]),
      ) as _i3.Future<List<_i4.NewsItem>>);
}
